// apps/frontend/src/components/timeline/CreatePostForm.vue
<template>
  <div class="bg-white/80 backdrop-blur-xl rounded-2xl border border-gray-200 p-6 mb-8 shadow-lg hover:shadow-xl transition-all">
    <form @submit.prevent="emit('submit')" class="flex flex-col gap-4">
      <Textarea
        :model-value="modelValue"
        @update:model-value="emit('update:modelValue', $event)"
        placeholder="What's on your mind?"
        :autoResize="true"
        rows="3"
        class="w-full border-2 border-gray-200 focus:border-green-500 focus:ring-0 rounded-xl transition-colors"
        :disabled="loading"
      />
      <div class="flex justify-end">
        <Button
          type="submit"
          :disabled="!modelValue.trim() || loading"
          :loading="loading"
          class="px-6 py-2.5 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 border-0 rounded-xl font-semibold text-white shadow-md hover:shadow-lg transition-all duration-200"
        >
          <template v-if="!loading">
            <span class="flex items-center justify-center gap-2">
              <i class="pi pi-send"></i>
              Post
            </span>
          </template>
          <template v-else>
            <span class="flex items-center justify-center gap-2">
              <i class="pi pi-spin pi-spinner"></i>
              Posting...
            </span>
          </template>
        </Button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import Textarea from 'primevue/textarea';
import Button from 'primevue/button';

interface Props {
  modelValue: string;
  loading?: boolean;
}

withDefaults(defineProps<Props>(), {
  loading: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
  submit: [];
}>();
</script>

// apps/frontend-react/src/components/timeline/CreatePostForm.tsx
import { FormEvent } from 'react';

interface CreatePostFormProps {
  value: string;
  onChange: (value: string) => void;
  loading?: boolean;
  onSubmit: () => void;
}

export default function CreatePostForm({ value, onChange, loading = false, onSubmit }: CreatePostFormProps) {
  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (value.trim() && !loading) {
      onSubmit();
    }
  }

  return (
    <div className="bg-white/80 backdrop-blur-xl rounded-2xl border border-gray-200 p-6 mb-8 shadow-lg hover:shadow-xl transition-all">
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <textarea
          placeholder="What's on your mind?"
          rows={3}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          disabled={loading}
          className="w-full border-2 border-gray-200 focus:border-green-500 focus:ring-0 rounded-xl transition-colors resize-none p-3"
        />
        <div className="flex justify-end">
          <button
            type="submit"
            disabled={!value.trim() || loading}
            className="px-6 py-2.5 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 border-0 rounded-xl font-semibold text-white shadow-md hover:shadow-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <span className="animate-spin">⏳</span>
                Posting...
              </span>
            ) : (
              <span className="flex items-center justify-center gap-2">
                <span>📤</span>
                Post
              </span>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
