// apps/frontend-react/src/views/NotFoundView.tsx
import { Link } from 'react-router-dom';

export default function NotFoundView() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-white via-green-50 to-emerald-100 flex items-center justify-center px-4">
      <div className="text-center">
        <h1 className="text-9xl font-bold text-gray-800 mb-4">404</h1>
        <h2 className="text-3xl font-semibold text-gray-700 mb-4">Page Not Found</h2>
        <p className="text-gray-600 mb-8">The page you're looking for doesn't exist.</p>
        <Link
          to="/home"
          className="inline-block px-6 py-3 bg-gradient-to-r from-green-500 to-emerald-600 text-white rounded-xl font-semibold hover:shadow-xl transition-shadow"
        >
          Go Home
        </Link>
      </div>
    </div>
  );
}

// apps/frontend/src/views/NotFoundView.vue
<template>
  <div class="not-found-view">
    <h1 class="text-4xl font-bold text-center mt-16">404</h1>
    <p class="text-center mt-4 text-gray-600">Page not found</p>
    <div class="text-center mt-8">
      <router-link
        to="/"
        class="text-blue-600 hover:text-blue-800 underline"
      >
        Go back home
      </router-link>
    </div>
  </div>
</template>

<script setup lang="ts">
// 404 view logic
</script>

<style scoped>
.not-found-view {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
}
</style>
