// apps/frontend-react/src/views/RegisterView.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import AuthLayout from '@/components/auth/AuthLayout';
import RegisterForm from '@/components/auth/RegisterForm';
import { UserRole, type RegisterData } from '@/types/auth';

export default function RegisterView() {
  const navigate = useNavigate();
  const { register, loading, error } = useAuth();
  const [formData, setFormData] = useState<RegisterData>({
    username: '',
    password: '',
    fullName: '',
    role: UserRole.USER,
  });
  const [confirmPassword, setConfirmPassword] = useState('');

  async function handleRegister() {
    if (formData.password !== confirmPassword) {
      return;
    }

    try {
      await register(formData);
      navigate('/timeline');
    } catch (err) {
      // Error is handled in the context
    }
  }

  return (
    <AuthLayout title="Create Account" subtitle="Join our community today!">
      <RegisterForm
        formData={formData}
        onFormDataChange={setFormData}
        confirmPassword={confirmPassword}
        onConfirmPasswordChange={setConfirmPassword}
        loading={loading}
        error={error}
        onSubmit={handleRegister}
      />
      <div className="mt-6 text-center">
        <p className="text-sm text-gray-600">
          Already have an account?{' '}
          <Link to="/login" className="font-medium text-green-600 hover:text-green-700">
            Sign in
          </Link>
        </p>
      </div>
    </AuthLayout>
  );
}

// apps/frontend/src/views/RegisterView.vue
<template>
  <AuthLayout
    title="Create Account"
    subtitle="Join our community today!"
  >
    <RegisterForm
      v-model="formData"
      v-model:confirm-password="confirmPassword"
      :loading="authStore.loading"
      :error="authStore.error"
      @submit="handleRegister"
    />

    <template #footer>
      <p class="text-sm text-gray-600">
        Already have an account?
        <RouterLink to="/login" class="font-medium text-green-600 hover:text-green-700">
          Sign in
        </RouterLink>
      </p>
    </template>
  </AuthLayout>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, RouterLink } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { UserRole, type RegisterData } from '@/types/auth';
import AuthLayout from '@/components/auth/AuthLayout.vue';
import RegisterForm from '@/components/auth/RegisterForm.vue';

const router = useRouter();
const authStore = useAuthStore();

const formData = ref<RegisterData>({
  username: '',
  password: '',
  fullName: '',
  role: UserRole.USER,
});

const confirmPassword = ref('');

async function handleRegister() {
  // Validate password confirmation
  if (formData.value.password !== confirmPassword.value) {
    authStore.error = 'Passwords do not match';
    return;
  }

  try {
    await authStore.register(formData.value);
    router.push('/timeline');
  } catch (error) {
    // Error is handled in the store
  }
}
</script>
