// apps/frontend/src/views/LoginView.vue
<template>
  <AuthLayout
    title="Sign In"
    subtitle="Welcome back! Please sign in to your account."
  >
    <LoginForm
      v-model="credentials"
      :loading="authStore.loading"
      :error="authStore.error"
      @submit="handleLogin"
    />

    <template #footer>
      <p class="text-sm text-gray-600">
        Don't have an account?
        <RouterLink to="/register" class="font-medium text-green-600 hover:text-green-700">
          Sign up
        </RouterLink>
      </p>
    </template>
  </AuthLayout>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, RouterLink } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import type { LoginCredentials } from '@/types/auth';
import AuthLayout from '@/components/auth/AuthLayout.vue';
import LoginForm from '@/components/auth/LoginForm.vue';

const router = useRouter();
const authStore = useAuthStore();

const credentials = ref<LoginCredentials>({
  username: '',
  password: '',
});

async function handleLogin() {
  try {
    await authStore.login(credentials.value);
    router.push('/timeline');
  } catch (error) {
    // Error is handled in the store
  }
}
</script>

// apps/frontend-react/src/views/LoginView.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import AuthLayout from '@/components/auth/AuthLayout';
import LoginForm from '@/components/auth/LoginForm';
import type { LoginCredentials } from '@/types/auth';

export default function LoginView() {
  const navigate = useNavigate();
  const { login, loading, error } = useAuth();
  const [credentials, setCredentials] = useState<LoginCredentials>({
    username: '',
    password: '',
  });

  async function handleLogin() {
    try {
      await login(credentials);
      navigate('/timeline');
    } catch (err) {
      // Error is handled in the context
    }
  }

  return (
    <AuthLayout title="Sign In" subtitle="Welcome back! Please sign in to your account.">
      <LoginForm
        credentials={credentials}
        onCredentialsChange={setCredentials}
        loading={loading}
        error={error}
        onSubmit={handleLogin}
      />
      <div className="mt-6 text-center">
        <p className="text-sm text-gray-600">
          Don't have an account?{' '}
          <Link to="/register" className="font-medium text-green-600 hover:text-green-700">
            Sign up
          </Link>
        </p>
      </div>
    </AuthLayout>
  );
}
